feat: RFC 7231 4 Request Methods
MyLittleWebServer/webserv pull request #143
Opened 2023-07-20 10:41 UTC by middlefitting

## 개요
- RFC 7231 4. Request Methods에 따라 프로그램을 개선합니다.
- 이미 RFC에 맞게 구현이 된 부분은 명시하지 않습니다.

## RFC 준수 개선 사항
- [x] 4.1 Overview
> 모든 범용 서버는 GET 및 HEAD 메서드를 지원해야 한다. 다른 모든 메서드는 선택사항이다. (OPTIONAL)
- [x] 4.3.2 HEAD
> HEAD 메서드는 GET과 동일하지만, 서버가 응답에서 메시지 본문을 전송하면 안 된다.(MUST NOT)
서버는 HEAD 요청에 응답하여 GET 요청과 동일한 헤더 필드를 전송해야 한다.(SHOULD)
- [x] 4.3.4 PUT
> 원서버는 PUT 요청으로 인식되지 않는 수신된 헤더 필드를 무시해야 한다.(SHOULD) (i.e., 그것들을 리소스 상태의 일부로 저장하지 마라).
- [x] 4.3.7 OPTIONS
> 응답에서 페이로드 본문을 전송하지 않으려면 서버는 “0”의 값을 가진 Content-Length 필드를 생성해야 한다.(MUST)

## 기존 개선
- RequestParser::checkAllowedMethods: 논리적으로 맞지 않는 로직이 있어 제거하였습니다.
- Makefile: HEAD.cpp 추가하였습니다.
- Client::bodyCheck() 메소드를 통해 리스폰스를 생성하기 직전 HEAD 메소드라면 body를 제거합니다.

## 기능 구현
- HEAD 메소드 구현
- OPTION 메소드 구현
- RequestParser::checkContentRangeHeader
- RequestParser::checkContentRangeHeader

## 문서화
- RequestParser::checkContentRangeHeader
- HEAD
- OPTION

2023-07-20 15:20 UTC, Clearsu commented on srcs/clients/request/request_parser/src/RequestParser.cpp
> -      (*dts.method == "DELETE" && methodInfo.at("POST") == true))
원래는 DELETE가 여기에서 걸려서 405에러가 뜨고 동작하지 않길래 post_body에만 DELETE가 동작하도록 넣은 조건문입니다 :)

2023-07-20 15:22 UTC, Clearsu requested changes
HEAD 구현 하시느라 고생 많으셨습니다. checkAllowedMethod 쪽 코멘트만 체크해주시면 될 것 같습니다.

2023-07-20 15:32 UTC, middlefitting commented on srcs/clients/request/request_parser/src/RequestParser.cpp
> -      (*dts.method == "DELETE" && methodInfo.at("POST") == true))
깊은 뜻이 있으셨군요, 특정 로케이션에 대해 허용 메소드를 추가하고 싶으시다면 
<img width="261" alt="image" src="https://github.com/MyLittleWebServer/webserv/assets/76660692/86ec88f6-562e-463c-8629-475336f9d000">
다음과 같이 , 기준으로 메소드를 추가하시면 됩니다!
혹시라도 delete가 모든 부분에서 허용되어야 하는 부분이라면 수정하도록 하겠습니다 ㅎㅎ

2023-07-20 15:33 UTC, middlefitting commented on srcs/clients/request/request_parser/src/RequestParser.cpp
> -      (*dts.method == "DELETE" && methodInfo.at("POST") == true))
해당 풀리퀘는 아직 진행중이어서 마무리하고 draft 해제하도록 하겠습니다!

2023-07-20 15:36 UTC, Clearsu commented on srcs/clients/request/request_parser/src/RequestParser.cpp
> -      (*dts.method == "DELETE" && methodInfo.at("POST") == true))
아하 아까 전화해서 질문 드리려고 했던 사항이었네요. 감사합니다 :)

2023-07-21 06:18 UTC, Clearsu approved these changes
HEAD와 OPTION이 구현 되었다니 가슴이 웅장해집니다. 고생 정말 많으셨습니다.

2023-07-21 06:27 UTC, cjho0316 commented on srcs/clients/client/include/Client.hpp
> +  void ressembleResponse();
typo: ressemble -> reassemble

2023-07-21 06:30 UTC, cjho0316 commented on srcs/clients/method/include/HEAD.hpp
> + * GETD을 상속받아 구현합니다.
typo: GETD -> GET :)

2023-07-21 06:36 UTC, cjho0316 approved these changes
bunch of pull requests GJ :) 👍

2023-07-21 06:38 UTC, merged